#============================================
#!This file was generated by the CBTek ProjectGen tool
#============================================
cmake_minimum_required(VERSION 3.0)
project(%%PROJECT_NAME%%)
set(LIBRARY_TYPE STATIC)
get_filename_component(PROJECT_ROOT ${CMAKE_CURRENT_BINARY_DIR} PATH)
set (CMAKE_MODULE_PATH "${PROJECT_SOURCE_DIR}/cmake")
include(${CMAKE_MODULE_PATH}/flags.cmake)
include(${CMAKE_MODULE_PATH}/build.cmake)
if (WIN32)
    set (PLATFORM WIN32)
endif()

#============================================
#Directories to include
#============================================
include_directories("${PROJECT_SOURCE_DIR}/common")
include_directories("${PROJECT_SOURCE_DIR}/products")

#============================================
#Add high level integration tests here
#============================================
add_subdirectory("${PROJECT_SOURCE_DIR}/products/test_%%PROJECT_NAME%%")

#============================================
#Add common libraries here
#============================================
#add_subdirectory("${PROJECT_SOURCE_DIR}/common/<YOUR COMMON LIBRARY>)

#============================================
#Add products here
#============================================
#add_subdirectory("${PROJECT_SOURCE_DIR}/products/<YOUR PRODUCT>)
